ALTER TABLE "Team" ADD COLUMN "power" INTEGER NOT NULL DEFAULT 10;
ALTER TABLE "User" ADD COLUMN "power" INTEGER NOT NULL DEFAULT 5;
ALTER TABLE "Location" ADD COLUMN "armor" INTEGER NOT NULL DEFAULT 8;

UPDATE "Location"
SET "armor" = COALESCE("power", 8);
